### ISSUE TITLE
Embed messages are broken

### ISSUE THREAD

**Issue by sx66627** [renzbobz/DiscordWebhook-PHP#2]
After January 3, messages stopped being sent.

`object(stdClass)#4 (4) {
  ["success"]=>
  bool(false)
  ["code"]=>
  int(400)
  ["curl_error"]=>
  string(0) ""
  ["body"]=>
  array(1) {
    ["allowed_mentions"]=>
    array(1) {
      [0]=>
      string(30) "Expected an object/dictionary."
    }
  }
}`

**Comment by sx66627** [comment]
fixed it myself

**Comment by renzbobz** [comment]
Sorry for not being around, I've now fixed it.
